### ISSUE TITLE
docstring in PEP224 style

### ISSUE THREAD

**Issue by sander76** [DanCardin/cappa#129]
Just discovered this project. Very nice! 
I also see my own repo (clipstick) being mentioned. I kinda feel honored ;-) !

I am considering cappa as an alternative to my own clipstick as I feel the argument parsing landscape is already way too
fragmented. Your project is also way more mature.

One question:
Have you considered (and would you accept a PR) docstring usage like this?:

```python
class MyClass:

    my_property:int
    """This is the docstring belonging to my_property"""
```

I know this is part of the rejected PEP 224. 
But it is also being re-discussed here: https://discuss.python.org/t/revisiting-attribute-docstrings/36413
From that discussion one can see that at least Flask is making use of the above docstring format.
Next to that both sphinx and mkdocs autodoc plugins support this.

Personally I do prefer the minimalism of the above over the rather verbose:

```python
class MyClass:
    my_property: Annotated[int, Arg(help="This is the docstirng belonging to my_property")] 
```

**Comment by DanCardin** [comment]
For what it's worth, today we support help from supported (google/numpy iirc) formats also. i.e.

```python
class MyClass:
    """doot.

    Arguments:
        my_property: This is the docstirng belonging to my_property
    """
    my_property: int
```

Ultimately not less verbose in this case, but perhaps more natural.

This was requested before in https://github.com/DanCardin/cappa/issues/9 but pawamoy ultimately wanted the `Doc` support, and it never went anywhere. I'm certainly not against the feature, i just find it really visually distracting personally, so i wont be using it :P.

With that said, I can probably quickly see how much of an investment supporting it would be.

**Comment by pawamoy** [comment]
I can see a use-case where both `typing.Doc` and attribute docstring below the assignment would be used: the first one for CLI usage, and the second one for API docs (or maybe the opposite?). Obviously, if the API docs extractor and Cappa both support `typing.Doc` and attribute docstrings, it can become confusing and require configuration to tell one or the other to use the former or latter...

To illustrate:

```python
@cappa.command
class MyCommand:
    my_option: Annotated[int, cappa.Arg(), Doc("Docs for CLI or for API?")]
    """Docs for API or for CLI?"""
```

**Comment by DanCardin** [comment]
(And the below is how all of the library works, given that Arg/etc info can be provided at varying levels of inference/specificity)

From cappa's perspective, it's in descending order of specificity: `help=` (arg specific) -> `Doc` (attribute specific, but explicitly) -> attribute docstring (attribute specific) -> class docstring (class specific), and that's how it's arriving at a specific selection on the resulant `Command` object. **Perhaps** we shouldn't be doing silent fallbacks and should instead warn/error on duplicates, but I was sort of imagining if you cared about code-level docstrings and such, you might switch to docstrings for internal use, and attribute-level for external use.

At least the built-in `docutils` extension has no way (currently) to make the above distinction. Not that it couldnt, but currently it's just directly using the help that the natural construction of the `Command` produces.

I could perhaps imagine help ultimately being a `list[Help]` instead of a `str`, to represent all the fallbacks in order; and then it would naturally/by default pick the first one, leaving open for something else to make that distinction. But i'm not entirely sure how useful this distinction would be, personally.

**Comment by DanCardin** [comment]
Turns out to not have been particularly hard, assuming i dont have any glaring bugs in how i'm finding the them

**Comment by sander76** [comment]
You. Are. Fast. !!

**Comment by DanCardin** [comment]
Heh! The nice thing about CLI libraries (or at least how i've written cappa anyway) is that it's super easy to write a new e2e test CLI in like 10loc, so it's **fairly** easy to add new features without a lot of guessing.

And a nice, straightforward extension of existing behavior is just :chef-kiss: the best!
